env:
  global:
# SONAR_GITHUB_TOKEN
  - secure: Cb5inPwNlfEREkhKa17tgThrTvFWV+RgfbIX3o2JZQ0Re9dlwNOoxxTd2NrYyRAWSj0LK/Dmev+wG56Jxovva2Kqt+xfpVF2y8C1BCNQlAXY4unoKy3pQ4dyk+iW2qHM0UuZDbyxLofPEKPi7GgoR/77fhdxHgvKPBRG1WixcDyz3NAjjP86M02gv5gY48S6DRPTGKX4kFii/VyEMpM62AKJBFvf6/NAB06E0zuV7l/DZn7JEYQ68upmB7CwhNA5NCMUqX1dVkGpSi4WFrCF2L38uIXDF8JF9nAJ8Cm9dZQobvTRGCeJHU+5t8a2q93zGcTae1147IqqmhbYvpW/69bzlsDsiv90Eg65yOYw8pUkY3FyX0r7jsm1Mo0tap8lYshh7Hc6VYcmDsaAp/XqHJOQWGwW3q6f694D8qe6jxxYMjXnfOuXJfQN/TmvrD++YHwxv1RPkpVXsmEL+IyuoY4PoY3oDRyX6CZ4HDn3zbp3S9Pv2jCGn0JVgZyXZY3lN/9AWPy3XPxuiPNOL8D6Y/dsJxhL4mCzRE3NlZ2m93RVk3mXLAbErwaAisglscpMb9/NDAydDsy8cuXK7Qq5anAfi516GJYr03zzEvz3KAxy3Dcxc1p4CQp65dnvnLgQqQpr/I0GmPRWUnCZSvOf5L5WuG0as8tM1CtD5A89aqI=
# GITHUB_TOKEN
  - secure: UEgI8RiP/oG9OhI85Cy/ZRk4GtbcjFSjo9YOvPq6F1J/syTkRioGQ6RQO0Y/91T+O5ZnCduSHAHZsAzqdbg7Ny2nL/8IvvtQZLFtNOfxnko2MJnzUhlsSvUFT9PGDGYtLf5DkvTc0VcjZnUSMBENV+905ms5jBdeXB8EaOB4Kgfu7CctiL4ebgZt4hbQjUybIDrrosm9SJ3UX6yIvBhj4c/mkHVJAnh24mnrSDYFXDs1uTsLyjK3VuYyqWCK2dMhBcAAGtCfpGp+LexSP+a3fO9PdEjldcE3rrXutvMd/LYKmaUifNFJhAg5M4Wh9xDL8jsN3X44xexPPXHnR0CaIc2ETLk/Sj/P7bn6eCG0xPckM2oIXoHA8MV6KnOmigxK89N5Z9gs/BNzNNy5bRnL+wg55X+58JLnfRHaPKwnnXaKXgM0vMNuX8wCf2OkPPEQEa2bfU5xH+nn5mToayWTqUNUb5Z4xalM8ZrGJFVFMgHfbtvKi/+RwOxk7KS2DCS1iJG4aWbhPt2DBPPxrNHSM4PgSS7Xt2DaOzANwmR5+4Fka4zYu0/qcq1rL5Bzng+v/brAurk0shdlWeyq7HpCiBGZs9zjB1WG1ea+QHwwOeAjtG7NEEIk2kbaYk4tL4MdGHN35EKcgIh/qlsPBAye27n7fsaCj/TGm56dJdOiNy0=
addons:
  sonarqube:
    branches:
    - master
language: python
matrix:
  include:
    - os: linux
      sudo;: required
      python: 2.7
      env: TOXENV=py27
    - os: linux
      sudo;: required
      python: 3.4
      env: TOXENV=py34
    - os: linux
      sudo;: required
      python: 3.5
      env: TOXENV=py35
    - os: linux
      sudo;: required
      python: 3.6
      env: TOXENV=py36

before_install:
- pip freeze
install:
- pip install tox
script:
- tox -e "{$TOXENV},flake8,docs"
after_script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then 
      sonar-scanner -X -Dsonar.login=${SONAR_GITHUB_TOKEN} -Dsonar.host.url=http://qalab.tk:82 ;
  else
      sonar-scanner -X -Dsonar.login=${SONAR_GITHUB_TOKEN} -Dsonar.host.url=http://qalab.tk:82 -Dsonar.github.repository=netzulo/qautils -Dsonar.github.pullRequest=${TRAVIS_PULL_REQUEST} -Dsonar.github.oauth=${GITHUB_TOKEN} -Dsonar.analysis.mode=preview ;
  fi
